/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChildrenChildIdRouteImport } from './routes/children.$childId'
import { Route as ChildrenChildIdRewardsRouteImport } from './routes/children.$childId_.rewards'
import { Route as ChildrenChildIdJourneyRouteImport } from './routes/children.$childId_.journey'
import { Route as ChildrenChildIdBadgesRouteImport } from './routes/children.$childId_.badges'
import { Route as ChildrenChildIdAddPointsRouteImport } from './routes/children.$childId_.add-points'
import { Route as ChildrenChildIdActivityHistoryRouteImport } from './routes/children.$childId_.activity-history'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenChildIdRoute = ChildrenChildIdRouteImport.update({
  id: '/children/$childId',
  path: '/children/$childId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenChildIdRewardsRoute = ChildrenChildIdRewardsRouteImport.update({
  id: '/children/$childId_/rewards',
  path: '/children/$childId/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenChildIdJourneyRoute = ChildrenChildIdJourneyRouteImport.update({
  id: '/children/$childId_/journey',
  path: '/children/$childId/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenChildIdBadgesRoute = ChildrenChildIdBadgesRouteImport.update({
  id: '/children/$childId_/badges',
  path: '/children/$childId/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenChildIdAddPointsRoute =
  ChildrenChildIdAddPointsRouteImport.update({
    id: '/children/$childId_/add-points',
    path: '/children/$childId/add-points',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChildrenChildIdActivityHistoryRoute =
  ChildrenChildIdActivityHistoryRouteImport.update({
    id: '/children/$childId_/activity-history',
    path: '/children/$childId/activity-history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/children/$childId': typeof ChildrenChildIdRoute
  '/children/$childId/activity-history': typeof ChildrenChildIdActivityHistoryRoute
  '/children/$childId/add-points': typeof ChildrenChildIdAddPointsRoute
  '/children/$childId/badges': typeof ChildrenChildIdBadgesRoute
  '/children/$childId/journey': typeof ChildrenChildIdJourneyRoute
  '/children/$childId/rewards': typeof ChildrenChildIdRewardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/children/$childId': typeof ChildrenChildIdRoute
  '/children/$childId/activity-history': typeof ChildrenChildIdActivityHistoryRoute
  '/children/$childId/add-points': typeof ChildrenChildIdAddPointsRoute
  '/children/$childId/badges': typeof ChildrenChildIdBadgesRoute
  '/children/$childId/journey': typeof ChildrenChildIdJourneyRoute
  '/children/$childId/rewards': typeof ChildrenChildIdRewardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/children/$childId': typeof ChildrenChildIdRoute
  '/children/$childId_/activity-history': typeof ChildrenChildIdActivityHistoryRoute
  '/children/$childId_/add-points': typeof ChildrenChildIdAddPointsRoute
  '/children/$childId_/badges': typeof ChildrenChildIdBadgesRoute
  '/children/$childId_/journey': typeof ChildrenChildIdJourneyRoute
  '/children/$childId_/rewards': typeof ChildrenChildIdRewardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/children/$childId'
    | '/children/$childId/activity-history'
    | '/children/$childId/add-points'
    | '/children/$childId/badges'
    | '/children/$childId/journey'
    | '/children/$childId/rewards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/children/$childId'
    | '/children/$childId/activity-history'
    | '/children/$childId/add-points'
    | '/children/$childId/badges'
    | '/children/$childId/journey'
    | '/children/$childId/rewards'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/children/$childId'
    | '/children/$childId_/activity-history'
    | '/children/$childId_/add-points'
    | '/children/$childId_/badges'
    | '/children/$childId_/journey'
    | '/children/$childId_/rewards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ChildrenChildIdRoute: typeof ChildrenChildIdRoute
  ChildrenChildIdActivityHistoryRoute: typeof ChildrenChildIdActivityHistoryRoute
  ChildrenChildIdAddPointsRoute: typeof ChildrenChildIdAddPointsRoute
  ChildrenChildIdBadgesRoute: typeof ChildrenChildIdBadgesRoute
  ChildrenChildIdJourneyRoute: typeof ChildrenChildIdJourneyRoute
  ChildrenChildIdRewardsRoute: typeof ChildrenChildIdRewardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/$childId': {
      id: '/children/$childId'
      path: '/children/$childId'
      fullPath: '/children/$childId'
      preLoaderRoute: typeof ChildrenChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/$childId_/rewards': {
      id: '/children/$childId_/rewards'
      path: '/children/$childId/rewards'
      fullPath: '/children/$childId/rewards'
      preLoaderRoute: typeof ChildrenChildIdRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/$childId_/journey': {
      id: '/children/$childId_/journey'
      path: '/children/$childId/journey'
      fullPath: '/children/$childId/journey'
      preLoaderRoute: typeof ChildrenChildIdJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/$childId_/badges': {
      id: '/children/$childId_/badges'
      path: '/children/$childId/badges'
      fullPath: '/children/$childId/badges'
      preLoaderRoute: typeof ChildrenChildIdBadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/$childId_/add-points': {
      id: '/children/$childId_/add-points'
      path: '/children/$childId/add-points'
      fullPath: '/children/$childId/add-points'
      preLoaderRoute: typeof ChildrenChildIdAddPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/$childId_/activity-history': {
      id: '/children/$childId_/activity-history'
      path: '/children/$childId/activity-history'
      fullPath: '/children/$childId/activity-history'
      preLoaderRoute: typeof ChildrenChildIdActivityHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ChildrenChildIdRoute: ChildrenChildIdRoute,
  ChildrenChildIdActivityHistoryRoute: ChildrenChildIdActivityHistoryRoute,
  ChildrenChildIdAddPointsRoute: ChildrenChildIdAddPointsRoute,
  ChildrenChildIdBadgesRoute: ChildrenChildIdBadgesRoute,
  ChildrenChildIdJourneyRoute: ChildrenChildIdJourneyRoute,
  ChildrenChildIdRewardsRoute: ChildrenChildIdRewardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
